---

- name: set redis user uid
  user: name=redis uid={{ redis_uid }} state=present
  when: redis_uid|default(False)

- name: reset redis folder and subfolder to new uid
  file: path={{ item }} owner={{ redis_uid }} group=redis follow=yes recurse=yes state=directory
  with_items:
    - "{{ redis_db_dir }}"
    - /var/log/redis
  when: redis_uid|default(False)

- name: redis-configure | Configure redis
  template: src=redis.conf.j2 dest={{redis_configuration}}
  notify:
   - redis restart
  register: redis_reconfigured

- name: Ensure the redis started
  service: name={{redis_service}} state=restarted enabled=yes
  changed_when: false
  when: redis_reconfigured

- name: redis-configure | Set the kernel parameter for vm overcommit
  sysctl: name=vm.overcommit_memory value=1 state=present
  when: redis_update_kernel|default(False)
