---

- name: redis-install | Add repository
  apt_repository: repo={{redis_ppa}} update_cache=yes
  when: redis_ppa

- name: redis-install | Install Redis
  apt: pkg={{item}}
  with_items:
    - python-selinux
    - daemon
    - redis-server

- name: redis-install | Setup init script
  template: src=redis-server.j2 dest=/etc/init.d/redis-server owner=root mode=744
